package com.fdzang.microservice.blog.article.dao.mapper;

import com.fdzang.microservice.blog.article.dao.domain.ArchivedateDO;
import com.fdzang.microservice.blog.article.dao.domain.ArchivedateDOExample;
import java.util.List;

public interface ArchivedateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    int insert(ArchivedateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    int insertSelective(ArchivedateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    List<ArchivedateDO> selectByExample(ArchivedateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    ArchivedateDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArchivedateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArchivedateDO record);
}