package com.fdzang.microservice.blog.article.dao.mapper;

import com.fdzang.microservice.blog.article.dao.domain.TagArticleDO;
import com.fdzang.microservice.blog.article.dao.domain.TagArticleDOExample;
import java.util.List;

public interface TagArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article
     *
     * @mbg.generated
     */
    int insert(TagArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article
     *
     * @mbg.generated
     */
    int insertSelective(TagArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article
     *
     * @mbg.generated
     */
    List<TagArticleDO> selectByExample(TagArticleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article
     *
     * @mbg.generated
     */
    TagArticleDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TagArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TagArticleDO record);
}