package com.fdzang.microservice.blog.article.dao.domain;

import java.util.ArrayList;
import java.util.List;

public class ArchivedateDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public ArchivedateDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountIsNull() {
            addCriterion("archivedate_article_count is null");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountIsNotNull() {
            addCriterion("archivedate_article_count is not null");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountEqualTo(Integer value) {
            addCriterion("archivedate_article_count =", value, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountNotEqualTo(Integer value) {
            addCriterion("archivedate_article_count <>", value, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountGreaterThan(Integer value) {
            addCriterion("archivedate_article_count >", value, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("archivedate_article_count >=", value, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountLessThan(Integer value) {
            addCriterion("archivedate_article_count <", value, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountLessThanOrEqualTo(Integer value) {
            addCriterion("archivedate_article_count <=", value, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountIn(List<Integer> values) {
            addCriterion("archivedate_article_count in", values, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountNotIn(List<Integer> values) {
            addCriterion("archivedate_article_count not in", values, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountBetween(Integer value1, Integer value2) {
            addCriterion("archivedate_article_count between", value1, value2, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedateArticleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("archivedate_article_count not between", value1, value2, "archivedateArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountIsNull() {
            addCriterion("archivedate_published_article_count is null");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountIsNotNull() {
            addCriterion("archivedate_published_article_count is not null");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountEqualTo(Integer value) {
            addCriterion("archivedate_published_article_count =", value, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountNotEqualTo(Integer value) {
            addCriterion("archivedate_published_article_count <>", value, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountGreaterThan(Integer value) {
            addCriterion("archivedate_published_article_count >", value, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("archivedate_published_article_count >=", value, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountLessThan(Integer value) {
            addCriterion("archivedate_published_article_count <", value, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountLessThanOrEqualTo(Integer value) {
            addCriterion("archivedate_published_article_count <=", value, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountIn(List<Integer> values) {
            addCriterion("archivedate_published_article_count in", values, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountNotIn(List<Integer> values) {
            addCriterion("archivedate_published_article_count not in", values, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountBetween(Integer value1, Integer value2) {
            addCriterion("archivedate_published_article_count between", value1, value2, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchivedatePublishedArticleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("archivedate_published_article_count not between", value1, value2, "archivedatePublishedArticleCount");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeIsNull() {
            addCriterion("archive_time is null");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeIsNotNull() {
            addCriterion("archive_time is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeEqualTo(Long value) {
            addCriterion("archive_time =", value, "archiveTime");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeNotEqualTo(Long value) {
            addCriterion("archive_time <>", value, "archiveTime");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeGreaterThan(Long value) {
            addCriterion("archive_time >", value, "archiveTime");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("archive_time >=", value, "archiveTime");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeLessThan(Long value) {
            addCriterion("archive_time <", value, "archiveTime");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeLessThanOrEqualTo(Long value) {
            addCriterion("archive_time <=", value, "archiveTime");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeIn(List<Long> values) {
            addCriterion("archive_time in", values, "archiveTime");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeNotIn(List<Long> values) {
            addCriterion("archive_time not in", values, "archiveTime");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeBetween(Long value1, Long value2) {
            addCriterion("archive_time between", value1, value2, "archiveTime");
            return (Criteria) this;
        }

        public Criteria andArchiveTimeNotBetween(Long value1, Long value2) {
            addCriterion("archive_time not between", value1, value2, "archiveTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table archivedate
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table archivedate
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}