package com.fdzang.microservice.blog.article.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table archivedate
 */
public class ArchivedateDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archivedate.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   存档日期文章计数，即某个月的文章总数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archivedate.archivedate_article_count
     *
     * @mbg.generated
     */
    private Integer archivedateArticleCount;

    /**
     * Database Column Remarks:
     *   存档日期已发布的文章计数，即某个月的已发布文章总数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archivedate.archivedate_published_article_count
     *
     * @mbg.generated
     */
    private Integer archivedatePublishedArticleCount;

    /**
     * Database Column Remarks:
     *   存档日期时间，该月份第一天的时间戳
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archivedate.archive_time
     *
     * @mbg.generated
     */
    private Long archiveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archivedate.id
     *
     * @return the value of archivedate.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archivedate.id
     *
     * @param id the value for archivedate.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archivedate.archivedate_article_count
     *
     * @return the value of archivedate.archivedate_article_count
     *
     * @mbg.generated
     */
    public Integer getArchivedateArticleCount() {
        return archivedateArticleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archivedate.archivedate_article_count
     *
     * @param archivedateArticleCount the value for archivedate.archivedate_article_count
     *
     * @mbg.generated
     */
    public void setArchivedateArticleCount(Integer archivedateArticleCount) {
        this.archivedateArticleCount = archivedateArticleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archivedate.archivedate_published_article_count
     *
     * @return the value of archivedate.archivedate_published_article_count
     *
     * @mbg.generated
     */
    public Integer getArchivedatePublishedArticleCount() {
        return archivedatePublishedArticleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archivedate.archivedate_published_article_count
     *
     * @param archivedatePublishedArticleCount the value for archivedate.archivedate_published_article_count
     *
     * @mbg.generated
     */
    public void setArchivedatePublishedArticleCount(Integer archivedatePublishedArticleCount) {
        this.archivedatePublishedArticleCount = archivedatePublishedArticleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archivedate.archive_time
     *
     * @return the value of archivedate.archive_time
     *
     * @mbg.generated
     */
    public Long getArchiveTime() {
        return archiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archivedate.archive_time
     *
     * @param archiveTime the value for archivedate.archive_time
     *
     * @mbg.generated
     */
    public void setArchiveTime(Long archiveTime) {
        this.archiveTime = archiveTime;
    }
}