package com.fdzang.microservice.blog.article.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table archivedate_article
 */
public class ArchivedateArticleDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archivedate_article.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   存档日期 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archivedate_article.archivedate_id
     *
     * @mbg.generated
     */
    private String archivedateId;

    /**
     * Database Column Remarks:
     *   文章 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archivedate_article.article_id
     *
     * @mbg.generated
     */
    private String articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archivedate_article.id
     *
     * @return the value of archivedate_article.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archivedate_article.id
     *
     * @param id the value for archivedate_article.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archivedate_article.archivedate_id
     *
     * @return the value of archivedate_article.archivedate_id
     *
     * @mbg.generated
     */
    public String getArchivedateId() {
        return archivedateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archivedate_article.archivedate_id
     *
     * @param archivedateId the value for archivedate_article.archivedate_id
     *
     * @mbg.generated
     */
    public void setArchivedateId(String archivedateId) {
        this.archivedateId = archivedateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archivedate_article.article_id
     *
     * @return the value of archivedate_article.article_id
     *
     * @mbg.generated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archivedate_article.article_id
     *
     * @param articleId the value for archivedate_article.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }
}