package com.fdzang.microservice.blog.article.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table article
 */
public class ArticleDOWithBLOBs extends ArticleDO {
    /**
     * Database Column Remarks:
     *   文章摘要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_abstract
     *
     * @mbg.generated
     */
    private String articleAbstract;

    /**
     * Database Column Remarks:
     *   文章标签，英文逗号分隔
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_tags
     *
     * @mbg.generated
     */
    private String articleTags;

    /**
     * Database Column Remarks:
     *   文章正文内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content
     *
     * @mbg.generated
     */
    private String articleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_abstract
     *
     * @return the value of article.article_abstract
     *
     * @mbg.generated
     */
    public String getArticleAbstract() {
        return articleAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_abstract
     *
     * @param articleAbstract the value for article.article_abstract
     *
     * @mbg.generated
     */
    public void setArticleAbstract(String articleAbstract) {
        this.articleAbstract = articleAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_tags
     *
     * @return the value of article.article_tags
     *
     * @mbg.generated
     */
    public String getArticleTags() {
        return articleTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_tags
     *
     * @param articleTags the value for article.article_tags
     *
     * @mbg.generated
     */
    public void setArticleTags(String articleTags) {
        this.articleTags = articleTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     *
     * @mbg.generated
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     *
     * @mbg.generated
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }
}