package com.fdzang.microservice.blog.article.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticleDOExample {

    protected Integer startPos;
    protected Integer pageSize;

    public Integer getStartPos() {
        return startPos;
    }

    public void setStartPos(Integer startPos) {
        this.startPos = startPos;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public ArticleDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNull() {
            addCriterion("article_title is null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNotNull() {
            addCriterion("article_title is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleEqualTo(String value) {
            addCriterion("article_title =", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotEqualTo(String value) {
            addCriterion("article_title <>", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThan(String value) {
            addCriterion("article_title >", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThanOrEqualTo(String value) {
            addCriterion("article_title >=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThan(String value) {
            addCriterion("article_title <", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThanOrEqualTo(String value) {
            addCriterion("article_title <=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLike(String value) {
            addCriterion("article_title like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotLike(String value) {
            addCriterion("article_title not like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIn(List<String> values) {
            addCriterion("article_title in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotIn(List<String> values) {
            addCriterion("article_title not in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleBetween(String value1, String value2) {
            addCriterion("article_title between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotBetween(String value1, String value2) {
            addCriterion("article_title not between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailIsNull() {
            addCriterion("article_author_email is null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailIsNotNull() {
            addCriterion("article_author_email is not null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailEqualTo(String value) {
            addCriterion("article_author_email =", value, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailNotEqualTo(String value) {
            addCriterion("article_author_email <>", value, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailGreaterThan(String value) {
            addCriterion("article_author_email >", value, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailGreaterThanOrEqualTo(String value) {
            addCriterion("article_author_email >=", value, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailLessThan(String value) {
            addCriterion("article_author_email <", value, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailLessThanOrEqualTo(String value) {
            addCriterion("article_author_email <=", value, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailLike(String value) {
            addCriterion("article_author_email like", value, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailNotLike(String value) {
            addCriterion("article_author_email not like", value, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailIn(List<String> values) {
            addCriterion("article_author_email in", values, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailNotIn(List<String> values) {
            addCriterion("article_author_email not in", values, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailBetween(String value1, String value2) {
            addCriterion("article_author_email between", value1, value2, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEmailNotBetween(String value1, String value2) {
            addCriterion("article_author_email not between", value1, value2, "articleAuthorEmail");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountIsNull() {
            addCriterion("article_comment_count is null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountIsNotNull() {
            addCriterion("article_comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountEqualTo(Integer value) {
            addCriterion("article_comment_count =", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountNotEqualTo(Integer value) {
            addCriterion("article_comment_count <>", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountGreaterThan(Integer value) {
            addCriterion("article_comment_count >", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_comment_count >=", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountLessThan(Integer value) {
            addCriterion("article_comment_count <", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("article_comment_count <=", value, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountIn(List<Integer> values) {
            addCriterion("article_comment_count in", values, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountNotIn(List<Integer> values) {
            addCriterion("article_comment_count not in", values, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountBetween(Integer value1, Integer value2) {
            addCriterion("article_comment_count between", value1, value2, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleCommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("article_comment_count not between", value1, value2, "articleCommentCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountIsNull() {
            addCriterion("article_view_count is null");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountIsNotNull() {
            addCriterion("article_view_count is not null");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountEqualTo(Integer value) {
            addCriterion("article_view_count =", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountNotEqualTo(Integer value) {
            addCriterion("article_view_count <>", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountGreaterThan(Integer value) {
            addCriterion("article_view_count >", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_view_count >=", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountLessThan(Integer value) {
            addCriterion("article_view_count <", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountLessThanOrEqualTo(Integer value) {
            addCriterion("article_view_count <=", value, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountIn(List<Integer> values) {
            addCriterion("article_view_count in", values, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountNotIn(List<Integer> values) {
            addCriterion("article_view_count not in", values, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountBetween(Integer value1, Integer value2) {
            addCriterion("article_view_count between", value1, value2, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticleViewCountNotBetween(Integer value1, Integer value2) {
            addCriterion("article_view_count not between", value1, value2, "articleViewCount");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkIsNull() {
            addCriterion("article_permalink is null");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkIsNotNull() {
            addCriterion("article_permalink is not null");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkEqualTo(String value) {
            addCriterion("article_permalink =", value, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkNotEqualTo(String value) {
            addCriterion("article_permalink <>", value, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkGreaterThan(String value) {
            addCriterion("article_permalink >", value, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkGreaterThanOrEqualTo(String value) {
            addCriterion("article_permalink >=", value, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkLessThan(String value) {
            addCriterion("article_permalink <", value, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkLessThanOrEqualTo(String value) {
            addCriterion("article_permalink <=", value, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkLike(String value) {
            addCriterion("article_permalink like", value, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkNotLike(String value) {
            addCriterion("article_permalink not like", value, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkIn(List<String> values) {
            addCriterion("article_permalink in", values, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkNotIn(List<String> values) {
            addCriterion("article_permalink not in", values, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkBetween(String value1, String value2) {
            addCriterion("article_permalink between", value1, value2, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticlePermalinkNotBetween(String value1, String value2) {
            addCriterion("article_permalink not between", value1, value2, "articlePermalink");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedIsNull() {
            addCriterion("article_had_been_published is null");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedIsNotNull() {
            addCriterion("article_had_been_published is not null");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedEqualTo(String value) {
            addCriterion("article_had_been_published =", value, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedNotEqualTo(String value) {
            addCriterion("article_had_been_published <>", value, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedGreaterThan(String value) {
            addCriterion("article_had_been_published >", value, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedGreaterThanOrEqualTo(String value) {
            addCriterion("article_had_been_published >=", value, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedLessThan(String value) {
            addCriterion("article_had_been_published <", value, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedLessThanOrEqualTo(String value) {
            addCriterion("article_had_been_published <=", value, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedLike(String value) {
            addCriterion("article_had_been_published like", value, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedNotLike(String value) {
            addCriterion("article_had_been_published not like", value, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedIn(List<String> values) {
            addCriterion("article_had_been_published in", values, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedNotIn(List<String> values) {
            addCriterion("article_had_been_published not in", values, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedBetween(String value1, String value2) {
            addCriterion("article_had_been_published between", value1, value2, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleHadBeenPublishedNotBetween(String value1, String value2) {
            addCriterion("article_had_been_published not between", value1, value2, "articleHadBeenPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedIsNull() {
            addCriterion("article_is_published is null");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedIsNotNull() {
            addCriterion("article_is_published is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedEqualTo(String value) {
            addCriterion("article_is_published =", value, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedNotEqualTo(String value) {
            addCriterion("article_is_published <>", value, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedGreaterThan(String value) {
            addCriterion("article_is_published >", value, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedGreaterThanOrEqualTo(String value) {
            addCriterion("article_is_published >=", value, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedLessThan(String value) {
            addCriterion("article_is_published <", value, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedLessThanOrEqualTo(String value) {
            addCriterion("article_is_published <=", value, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedLike(String value) {
            addCriterion("article_is_published like", value, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedNotLike(String value) {
            addCriterion("article_is_published not like", value, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedIn(List<String> values) {
            addCriterion("article_is_published in", values, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedNotIn(List<String> values) {
            addCriterion("article_is_published not in", values, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedBetween(String value1, String value2) {
            addCriterion("article_is_published between", value1, value2, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticleIsPublishedNotBetween(String value1, String value2) {
            addCriterion("article_is_published not between", value1, value2, "articleIsPublished");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopIsNull() {
            addCriterion("article_put_top is null");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopIsNotNull() {
            addCriterion("article_put_top is not null");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopEqualTo(String value) {
            addCriterion("article_put_top =", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopNotEqualTo(String value) {
            addCriterion("article_put_top <>", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopGreaterThan(String value) {
            addCriterion("article_put_top >", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopGreaterThanOrEqualTo(String value) {
            addCriterion("article_put_top >=", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopLessThan(String value) {
            addCriterion("article_put_top <", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopLessThanOrEqualTo(String value) {
            addCriterion("article_put_top <=", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopLike(String value) {
            addCriterion("article_put_top like", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopNotLike(String value) {
            addCriterion("article_put_top not like", value, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopIn(List<String> values) {
            addCriterion("article_put_top in", values, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopNotIn(List<String> values) {
            addCriterion("article_put_top not in", values, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopBetween(String value1, String value2) {
            addCriterion("article_put_top between", value1, value2, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticlePutTopNotBetween(String value1, String value2) {
            addCriterion("article_put_top not between", value1, value2, "articlePutTop");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateIsNull() {
            addCriterion("article_create_date is null");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateIsNotNull() {
            addCriterion("article_create_date is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateEqualTo(Date value) {
            addCriterion("article_create_date =", value, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateNotEqualTo(Date value) {
            addCriterion("article_create_date <>", value, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateGreaterThan(Date value) {
            addCriterion("article_create_date >", value, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("article_create_date >=", value, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateLessThan(Date value) {
            addCriterion("article_create_date <", value, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("article_create_date <=", value, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateIn(List<Date> values) {
            addCriterion("article_create_date in", values, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateNotIn(List<Date> values) {
            addCriterion("article_create_date not in", values, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateBetween(Date value1, Date value2) {
            addCriterion("article_create_date between", value1, value2, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("article_create_date not between", value1, value2, "articleCreateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateIsNull() {
            addCriterion("article_update_date is null");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateIsNotNull() {
            addCriterion("article_update_date is not null");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateEqualTo(Date value) {
            addCriterion("article_update_date =", value, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateNotEqualTo(Date value) {
            addCriterion("article_update_date <>", value, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateGreaterThan(Date value) {
            addCriterion("article_update_date >", value, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("article_update_date >=", value, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateLessThan(Date value) {
            addCriterion("article_update_date <", value, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("article_update_date <=", value, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateIn(List<Date> values) {
            addCriterion("article_update_date in", values, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateNotIn(List<Date> values) {
            addCriterion("article_update_date not in", values, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateBetween(Date value1, Date value2) {
            addCriterion("article_update_date between", value1, value2, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("article_update_date not between", value1, value2, "articleUpdateDate");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleIsNull() {
            addCriterion("article_random_double is null");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleIsNotNull() {
            addCriterion("article_random_double is not null");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleEqualTo(Double value) {
            addCriterion("article_random_double =", value, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleNotEqualTo(Double value) {
            addCriterion("article_random_double <>", value, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleGreaterThan(Double value) {
            addCriterion("article_random_double >", value, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleGreaterThanOrEqualTo(Double value) {
            addCriterion("article_random_double >=", value, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleLessThan(Double value) {
            addCriterion("article_random_double <", value, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleLessThanOrEqualTo(Double value) {
            addCriterion("article_random_double <=", value, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleIn(List<Double> values) {
            addCriterion("article_random_double in", values, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleNotIn(List<Double> values) {
            addCriterion("article_random_double not in", values, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleBetween(Double value1, Double value2) {
            addCriterion("article_random_double between", value1, value2, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleRandomDoubleNotBetween(Double value1, Double value2) {
            addCriterion("article_random_double not between", value1, value2, "articleRandomDouble");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdIsNull() {
            addCriterion("article_sign_id is null");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdIsNotNull() {
            addCriterion("article_sign_id is not null");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdEqualTo(String value) {
            addCriterion("article_sign_id =", value, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdNotEqualTo(String value) {
            addCriterion("article_sign_id <>", value, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdGreaterThan(String value) {
            addCriterion("article_sign_id >", value, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdGreaterThanOrEqualTo(String value) {
            addCriterion("article_sign_id >=", value, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdLessThan(String value) {
            addCriterion("article_sign_id <", value, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdLessThanOrEqualTo(String value) {
            addCriterion("article_sign_id <=", value, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdLike(String value) {
            addCriterion("article_sign_id like", value, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdNotLike(String value) {
            addCriterion("article_sign_id not like", value, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdIn(List<String> values) {
            addCriterion("article_sign_id in", values, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdNotIn(List<String> values) {
            addCriterion("article_sign_id not in", values, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdBetween(String value1, String value2) {
            addCriterion("article_sign_id between", value1, value2, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleSignIdNotBetween(String value1, String value2) {
            addCriterion("article_sign_id not between", value1, value2, "articleSignId");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableIsNull() {
            addCriterion("article_commentable is null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableIsNotNull() {
            addCriterion("article_commentable is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableEqualTo(String value) {
            addCriterion("article_commentable =", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableNotEqualTo(String value) {
            addCriterion("article_commentable <>", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableGreaterThan(String value) {
            addCriterion("article_commentable >", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableGreaterThanOrEqualTo(String value) {
            addCriterion("article_commentable >=", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableLessThan(String value) {
            addCriterion("article_commentable <", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableLessThanOrEqualTo(String value) {
            addCriterion("article_commentable <=", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableLike(String value) {
            addCriterion("article_commentable like", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableNotLike(String value) {
            addCriterion("article_commentable not like", value, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableIn(List<String> values) {
            addCriterion("article_commentable in", values, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableNotIn(List<String> values) {
            addCriterion("article_commentable not in", values, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableBetween(String value1, String value2) {
            addCriterion("article_commentable between", value1, value2, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleCommentableNotBetween(String value1, String value2) {
            addCriterion("article_commentable not between", value1, value2, "articleCommentable");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdIsNull() {
            addCriterion("article_view_pwd is null");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdIsNotNull() {
            addCriterion("article_view_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdEqualTo(String value) {
            addCriterion("article_view_pwd =", value, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdNotEqualTo(String value) {
            addCriterion("article_view_pwd <>", value, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdGreaterThan(String value) {
            addCriterion("article_view_pwd >", value, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdGreaterThanOrEqualTo(String value) {
            addCriterion("article_view_pwd >=", value, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdLessThan(String value) {
            addCriterion("article_view_pwd <", value, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdLessThanOrEqualTo(String value) {
            addCriterion("article_view_pwd <=", value, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdLike(String value) {
            addCriterion("article_view_pwd like", value, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdNotLike(String value) {
            addCriterion("article_view_pwd not like", value, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdIn(List<String> values) {
            addCriterion("article_view_pwd in", values, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdNotIn(List<String> values) {
            addCriterion("article_view_pwd not in", values, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdBetween(String value1, String value2) {
            addCriterion("article_view_pwd between", value1, value2, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleViewPwdNotBetween(String value1, String value2) {
            addCriterion("article_view_pwd not between", value1, value2, "articleViewPwd");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeIsNull() {
            addCriterion("article_editor_type is null");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeIsNotNull() {
            addCriterion("article_editor_type is not null");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeEqualTo(String value) {
            addCriterion("article_editor_type =", value, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeNotEqualTo(String value) {
            addCriterion("article_editor_type <>", value, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeGreaterThan(String value) {
            addCriterion("article_editor_type >", value, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("article_editor_type >=", value, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeLessThan(String value) {
            addCriterion("article_editor_type <", value, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeLessThanOrEqualTo(String value) {
            addCriterion("article_editor_type <=", value, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeLike(String value) {
            addCriterion("article_editor_type like", value, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeNotLike(String value) {
            addCriterion("article_editor_type not like", value, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeIn(List<String> values) {
            addCriterion("article_editor_type in", values, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeNotIn(List<String> values) {
            addCriterion("article_editor_type not in", values, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeBetween(String value1, String value2) {
            addCriterion("article_editor_type between", value1, value2, "articleEditorType");
            return (Criteria) this;
        }

        public Criteria andArticleEditorTypeNotBetween(String value1, String value2) {
            addCriterion("article_editor_type not between", value1, value2, "articleEditorType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}