package com.fdzang.microservice.blog.article.dao.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table article
 */
public class ArticleDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   文章标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_title
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     * Database Column Remarks:
     *   文章作者邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_author_email
     *
     * @mbg.generated
     */
    private String articleAuthorEmail;

    /**
     * Database Column Remarks:
     *   文章评论计数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_comment_count
     *
     * @mbg.generated
     */
    private Integer articleCommentCount;

    /**
     * Database Column Remarks:
     *   文章浏览计数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_view_count
     *
     * @mbg.generated
     */
    private Integer articleViewCount;

    /**
     * Database Column Remarks:
     *   文章访问路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_permalink
     *
     * @mbg.generated
     */
    private String articlePermalink;

    /**
     * Database Column Remarks:
     *   文章是否已经发布过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_had_been_published
     *
     * @mbg.generated
     */
    private String articleHadBeenPublished;

    /**
     * Database Column Remarks:
     *   文章是否处于已发布状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_is_published
     *
     * @mbg.generated
     */
    private String articleIsPublished;

    /**
     * Database Column Remarks:
     *   文章是否置顶
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_put_top
     *
     * @mbg.generated
     */
    private String articlePutTop;

    /**
     * Database Column Remarks:
     *   文章创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_create_date
     *
     * @mbg.generated
     */
    private Date articleCreateDate;

    /**
     * Database Column Remarks:
     *   文章更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_update_date
     *
     * @mbg.generated
     */
    private Date articleUpdateDate;

    /**
     * Database Column Remarks:
     *   文章随机数，用于快速查询随机文章列表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_random_double
     *
     * @mbg.generated
     */
    private Double articleRandomDouble;

    /**
     * Database Column Remarks:
     *   文章关联的签名档 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_sign_id
     *
     * @mbg.generated
     */
    private String articleSignId;

    /**
     * Database Column Remarks:
     *   文章是否可以评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_commentable
     *
     * @mbg.generated
     */
    private String articleCommentable;

    /**
     * Database Column Remarks:
     *   文章浏览密码，留空为不设置访问密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_view_pwd
     *
     * @mbg.generated
     */
    private String articleViewPwd;

    /**
     * Database Column Remarks:
     *   文章编辑器类型，目前仅支持 CodeMirror-Markdown
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_editor_type
     *
     * @mbg.generated
     */
    private String articleEditorType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_title
     *
     * @return the value of article.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_title
     *
     * @param articleTitle the value for article.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_author_email
     *
     * @return the value of article.article_author_email
     *
     * @mbg.generated
     */
    public String getArticleAuthorEmail() {
        return articleAuthorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_author_email
     *
     * @param articleAuthorEmail the value for article.article_author_email
     *
     * @mbg.generated
     */
    public void setArticleAuthorEmail(String articleAuthorEmail) {
        this.articleAuthorEmail = articleAuthorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_comment_count
     *
     * @return the value of article.article_comment_count
     *
     * @mbg.generated
     */
    public Integer getArticleCommentCount() {
        return articleCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_comment_count
     *
     * @param articleCommentCount the value for article.article_comment_count
     *
     * @mbg.generated
     */
    public void setArticleCommentCount(Integer articleCommentCount) {
        this.articleCommentCount = articleCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_view_count
     *
     * @return the value of article.article_view_count
     *
     * @mbg.generated
     */
    public Integer getArticleViewCount() {
        return articleViewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_view_count
     *
     * @param articleViewCount the value for article.article_view_count
     *
     * @mbg.generated
     */
    public void setArticleViewCount(Integer articleViewCount) {
        this.articleViewCount = articleViewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_permalink
     *
     * @return the value of article.article_permalink
     *
     * @mbg.generated
     */
    public String getArticlePermalink() {
        return articlePermalink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_permalink
     *
     * @param articlePermalink the value for article.article_permalink
     *
     * @mbg.generated
     */
    public void setArticlePermalink(String articlePermalink) {
        this.articlePermalink = articlePermalink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_had_been_published
     *
     * @return the value of article.article_had_been_published
     *
     * @mbg.generated
     */
    public String getArticleHadBeenPublished() {
        return articleHadBeenPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_had_been_published
     *
     * @param articleHadBeenPublished the value for article.article_had_been_published
     *
     * @mbg.generated
     */
    public void setArticleHadBeenPublished(String articleHadBeenPublished) {
        this.articleHadBeenPublished = articleHadBeenPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_is_published
     *
     * @return the value of article.article_is_published
     *
     * @mbg.generated
     */
    public String getArticleIsPublished() {
        return articleIsPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_is_published
     *
     * @param articleIsPublished the value for article.article_is_published
     *
     * @mbg.generated
     */
    public void setArticleIsPublished(String articleIsPublished) {
        this.articleIsPublished = articleIsPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_put_top
     *
     * @return the value of article.article_put_top
     *
     * @mbg.generated
     */
    public String getArticlePutTop() {
        return articlePutTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_put_top
     *
     * @param articlePutTop the value for article.article_put_top
     *
     * @mbg.generated
     */
    public void setArticlePutTop(String articlePutTop) {
        this.articlePutTop = articlePutTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_create_date
     *
     * @return the value of article.article_create_date
     *
     * @mbg.generated
     */
    public Date getArticleCreateDate() {
        return articleCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_create_date
     *
     * @param articleCreateDate the value for article.article_create_date
     *
     * @mbg.generated
     */
    public void setArticleCreateDate(Date articleCreateDate) {
        this.articleCreateDate = articleCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_update_date
     *
     * @return the value of article.article_update_date
     *
     * @mbg.generated
     */
    public Date getArticleUpdateDate() {
        return articleUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_update_date
     *
     * @param articleUpdateDate the value for article.article_update_date
     *
     * @mbg.generated
     */
    public void setArticleUpdateDate(Date articleUpdateDate) {
        this.articleUpdateDate = articleUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_random_double
     *
     * @return the value of article.article_random_double
     *
     * @mbg.generated
     */
    public Double getArticleRandomDouble() {
        return articleRandomDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_random_double
     *
     * @param articleRandomDouble the value for article.article_random_double
     *
     * @mbg.generated
     */
    public void setArticleRandomDouble(Double articleRandomDouble) {
        this.articleRandomDouble = articleRandomDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_sign_id
     *
     * @return the value of article.article_sign_id
     *
     * @mbg.generated
     */
    public String getArticleSignId() {
        return articleSignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_sign_id
     *
     * @param articleSignId the value for article.article_sign_id
     *
     * @mbg.generated
     */
    public void setArticleSignId(String articleSignId) {
        this.articleSignId = articleSignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_commentable
     *
     * @return the value of article.article_commentable
     *
     * @mbg.generated
     */
    public String getArticleCommentable() {
        return articleCommentable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_commentable
     *
     * @param articleCommentable the value for article.article_commentable
     *
     * @mbg.generated
     */
    public void setArticleCommentable(String articleCommentable) {
        this.articleCommentable = articleCommentable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_view_pwd
     *
     * @return the value of article.article_view_pwd
     *
     * @mbg.generated
     */
    public String getArticleViewPwd() {
        return articleViewPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_view_pwd
     *
     * @param articleViewPwd the value for article.article_view_pwd
     *
     * @mbg.generated
     */
    public void setArticleViewPwd(String articleViewPwd) {
        this.articleViewPwd = articleViewPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_editor_type
     *
     * @return the value of article.article_editor_type
     *
     * @mbg.generated
     */
    public String getArticleEditorType() {
        return articleEditorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_editor_type
     *
     * @param articleEditorType the value for article.article_editor_type
     *
     * @mbg.generated
     */
    public void setArticleEditorType(String articleEditorType) {
        this.articleEditorType = articleEditorType;
    }
}