package com.fdzang.microservice.blog.article.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comment
 */
public class CommentDOWithBLOBs extends CommentDO {
    /**
     * Database Column Remarks:
     *   评论内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_content
     *
     * @mbg.generated
     */
    private String commentContent;

    /**
     * Database Column Remarks:
     *   评论人头像图片链接地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_thumbnail_url
     *
     * @mbg.generated
     */
    private String commentThumbnailUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_content
     *
     * @return the value of comment.comment_content
     *
     * @mbg.generated
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_content
     *
     * @param commentContent the value for comment.comment_content
     *
     * @mbg.generated
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_thumbnail_url
     *
     * @return the value of comment.comment_thumbnail_url
     *
     * @mbg.generated
     */
    public String getCommentThumbnailUrl() {
        return commentThumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_thumbnail_url
     *
     * @param commentThumbnailUrl the value for comment.comment_thumbnail_url
     *
     * @mbg.generated
     */
    public void setCommentThumbnailUrl(String commentThumbnailUrl) {
        this.commentThumbnailUrl = commentThumbnailUrl;
    }
}