package com.fdzang.microservice.blog.article.dao.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comment
 */
public class CommentDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   评论时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_date
     *
     * @mbg.generated
     */
    private Date commentDate;

    /**
     * Database Column Remarks:
     *   评论人邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_email
     *
     * @mbg.generated
     */
    private String commentEmail;

    /**
     * Database Column Remarks:
     *   评论人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_name
     *
     * @mbg.generated
     */
    private String commentName;

    /**
     * Database Column Remarks:
     *   评论的文章/页面的 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_article_id
     *
     * @mbg.generated
     */
    private String commentArticleId;

    /**
     * Database Column Remarks:
     *   评论访问路径，带 # 锚点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_sharp_url
     *
     * @mbg.generated
     */
    private String commentSharpUrl;

    /**
     * Database Column Remarks:
     *   评论人链接地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_url
     *
     * @mbg.generated
     */
    private String commentUrl;

    /**
     * Database Column Remarks:
     *   评论回复时原始的评论 id，即父评论 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_original_comment_id
     *
     * @mbg.generated
     */
    private String commentOriginalCommentId;

    /**
     * Database Column Remarks:
     *   评论回复时原始的评论人名称，即父评论人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_original_comment_name
     *
     * @mbg.generated
     */
    private String commentOriginalCommentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_date
     *
     * @return the value of comment.comment_date
     *
     * @mbg.generated
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_date
     *
     * @param commentDate the value for comment.comment_date
     *
     * @mbg.generated
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_email
     *
     * @return the value of comment.comment_email
     *
     * @mbg.generated
     */
    public String getCommentEmail() {
        return commentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_email
     *
     * @param commentEmail the value for comment.comment_email
     *
     * @mbg.generated
     */
    public void setCommentEmail(String commentEmail) {
        this.commentEmail = commentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_name
     *
     * @return the value of comment.comment_name
     *
     * @mbg.generated
     */
    public String getCommentName() {
        return commentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_name
     *
     * @param commentName the value for comment.comment_name
     *
     * @mbg.generated
     */
    public void setCommentName(String commentName) {
        this.commentName = commentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_article_id
     *
     * @return the value of comment.comment_article_id
     *
     * @mbg.generated
     */
    public String getCommentArticleId() {
        return commentArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_article_id
     *
     * @param commentArticleId the value for comment.comment_article_id
     *
     * @mbg.generated
     */
    public void setCommentArticleId(String commentArticleId) {
        this.commentArticleId = commentArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_sharp_url
     *
     * @return the value of comment.comment_sharp_url
     *
     * @mbg.generated
     */
    public String getCommentSharpUrl() {
        return commentSharpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_sharp_url
     *
     * @param commentSharpUrl the value for comment.comment_sharp_url
     *
     * @mbg.generated
     */
    public void setCommentSharpUrl(String commentSharpUrl) {
        this.commentSharpUrl = commentSharpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_url
     *
     * @return the value of comment.comment_url
     *
     * @mbg.generated
     */
    public String getCommentUrl() {
        return commentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_url
     *
     * @param commentUrl the value for comment.comment_url
     *
     * @mbg.generated
     */
    public void setCommentUrl(String commentUrl) {
        this.commentUrl = commentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_original_comment_id
     *
     * @return the value of comment.comment_original_comment_id
     *
     * @mbg.generated
     */
    public String getCommentOriginalCommentId() {
        return commentOriginalCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_original_comment_id
     *
     * @param commentOriginalCommentId the value for comment.comment_original_comment_id
     *
     * @mbg.generated
     */
    public void setCommentOriginalCommentId(String commentOriginalCommentId) {
        this.commentOriginalCommentId = commentOriginalCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_original_comment_name
     *
     * @return the value of comment.comment_original_comment_name
     *
     * @mbg.generated
     */
    public String getCommentOriginalCommentName() {
        return commentOriginalCommentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_original_comment_name
     *
     * @param commentOriginalCommentName the value for comment.comment_original_comment_name
     *
     * @mbg.generated
     */
    public void setCommentOriginalCommentName(String commentOriginalCommentName) {
        this.commentOriginalCommentName = commentOriginalCommentName;
    }
}