package com.fdzang.microservice.blog.article.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tag_article
 */
public class TagArticleDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_article.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   文章 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_article.article_id
     *
     * @mbg.generated
     */
    private String articleId;

    /**
     * Database Column Remarks:
     *   标签 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_article.tag_id
     *
     * @mbg.generated
     */
    private String tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_article.id
     *
     * @return the value of tag_article.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_article.id
     *
     * @param id the value for tag_article.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_article.article_id
     *
     * @return the value of tag_article.article_id
     *
     * @mbg.generated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_article.article_id
     *
     * @param articleId the value for tag_article.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_article.tag_id
     *
     * @return the value of tag_article.tag_id
     *
     * @mbg.generated
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_article.tag_id
     *
     * @param tagId the value for tag_article.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(String tagId) {
        this.tagId = tagId;
    }
}