package com.fdzang.microservice.blog.article.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tag
 */
public class TagDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   标签关联的已发布文章计数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_published_ref_count
     *
     * @mbg.generated
     */
    private Integer tagPublishedRefCount;

    /**
     * Database Column Remarks:
     *   标签关联的文章计数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_reference_count
     *
     * @mbg.generated
     */
    private Integer tagReferenceCount;

    /**
     * Database Column Remarks:
     *   标签标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_title
     *
     * @mbg.generated
     */
    private String tagTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_published_ref_count
     *
     * @return the value of tag.tag_published_ref_count
     *
     * @mbg.generated
     */
    public Integer getTagPublishedRefCount() {
        return tagPublishedRefCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_published_ref_count
     *
     * @param tagPublishedRefCount the value for tag.tag_published_ref_count
     *
     * @mbg.generated
     */
    public void setTagPublishedRefCount(Integer tagPublishedRefCount) {
        this.tagPublishedRefCount = tagPublishedRefCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_reference_count
     *
     * @return the value of tag.tag_reference_count
     *
     * @mbg.generated
     */
    public Integer getTagReferenceCount() {
        return tagReferenceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_reference_count
     *
     * @param tagReferenceCount the value for tag.tag_reference_count
     *
     * @mbg.generated
     */
    public void setTagReferenceCount(Integer tagReferenceCount) {
        this.tagReferenceCount = tagReferenceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_title
     *
     * @return the value of tag.tag_title
     *
     * @mbg.generated
     */
    public String getTagTitle() {
        return tagTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_title
     *
     * @param tagTitle the value for tag.tag_title
     *
     * @mbg.generated
     */
    public void setTagTitle(String tagTitle) {
        this.tagTitle = tagTitle;
    }
}