package com.fdzang.microservice.blog.article.dao.domain;

import java.util.ArrayList;
import java.util.List;

public class TagDOExample {
    protected Integer startPos;
    protected Integer pageSize;

    public Integer getStartPos() {
        return startPos;
    }

    public void setStartPos(Integer startPos) {
        this.startPos = startPos;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public TagDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tag
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountIsNull() {
            addCriterion("tag_published_ref_count is null");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountIsNotNull() {
            addCriterion("tag_published_ref_count is not null");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountEqualTo(Integer value) {
            addCriterion("tag_published_ref_count =", value, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountNotEqualTo(Integer value) {
            addCriterion("tag_published_ref_count <>", value, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountGreaterThan(Integer value) {
            addCriterion("tag_published_ref_count >", value, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("tag_published_ref_count >=", value, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountLessThan(Integer value) {
            addCriterion("tag_published_ref_count <", value, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountLessThanOrEqualTo(Integer value) {
            addCriterion("tag_published_ref_count <=", value, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountIn(List<Integer> values) {
            addCriterion("tag_published_ref_count in", values, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountNotIn(List<Integer> values) {
            addCriterion("tag_published_ref_count not in", values, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountBetween(Integer value1, Integer value2) {
            addCriterion("tag_published_ref_count between", value1, value2, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagPublishedRefCountNotBetween(Integer value1, Integer value2) {
            addCriterion("tag_published_ref_count not between", value1, value2, "tagPublishedRefCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountIsNull() {
            addCriterion("tag_reference_count is null");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountIsNotNull() {
            addCriterion("tag_reference_count is not null");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountEqualTo(Integer value) {
            addCriterion("tag_reference_count =", value, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountNotEqualTo(Integer value) {
            addCriterion("tag_reference_count <>", value, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountGreaterThan(Integer value) {
            addCriterion("tag_reference_count >", value, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("tag_reference_count >=", value, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountLessThan(Integer value) {
            addCriterion("tag_reference_count <", value, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountLessThanOrEqualTo(Integer value) {
            addCriterion("tag_reference_count <=", value, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountIn(List<Integer> values) {
            addCriterion("tag_reference_count in", values, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountNotIn(List<Integer> values) {
            addCriterion("tag_reference_count not in", values, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountBetween(Integer value1, Integer value2) {
            addCriterion("tag_reference_count between", value1, value2, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagReferenceCountNotBetween(Integer value1, Integer value2) {
            addCriterion("tag_reference_count not between", value1, value2, "tagReferenceCount");
            return (Criteria) this;
        }

        public Criteria andTagTitleIsNull() {
            addCriterion("tag_title is null");
            return (Criteria) this;
        }

        public Criteria andTagTitleIsNotNull() {
            addCriterion("tag_title is not null");
            return (Criteria) this;
        }

        public Criteria andTagTitleEqualTo(String value) {
            addCriterion("tag_title =", value, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleNotEqualTo(String value) {
            addCriterion("tag_title <>", value, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleGreaterThan(String value) {
            addCriterion("tag_title >", value, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleGreaterThanOrEqualTo(String value) {
            addCriterion("tag_title >=", value, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleLessThan(String value) {
            addCriterion("tag_title <", value, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleLessThanOrEqualTo(String value) {
            addCriterion("tag_title <=", value, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleLike(String value) {
            addCriterion("tag_title like", value, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleNotLike(String value) {
            addCriterion("tag_title not like", value, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleIn(List<String> values) {
            addCriterion("tag_title in", values, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleNotIn(List<String> values) {
            addCriterion("tag_title not in", values, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleBetween(String value1, String value2) {
            addCriterion("tag_title between", value1, value2, "tagTitle");
            return (Criteria) this;
        }

        public Criteria andTagTitleNotBetween(String value1, String value2) {
            addCriterion("tag_title not between", value1, value2, "tagTitle");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tag
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tag
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}