spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.78.121.110:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/
  instance:
    prefer-ip-address: true