package com.fdzang.microservice.blog.ucenter.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table link
 */
public class LinkDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   链接地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_address
     *
     * @mbg.generated
     */
    private String linkAddress;

    /**
     * Database Column Remarks:
     *   链接描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_description
     *
     * @mbg.generated
     */
    private String linkDescription;

    /**
     * Database Column Remarks:
     *   链接展现的排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_order
     *
     * @mbg.generated
     */
    private Integer linkOrder;

    /**
     * Database Column Remarks:
     *   链接标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link_title
     *
     * @mbg.generated
     */
    private String linkTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.id
     *
     * @return the value of link.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.id
     *
     * @param id the value for link.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_address
     *
     * @return the value of link.link_address
     *
     * @mbg.generated
     */
    public String getLinkAddress() {
        return linkAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_address
     *
     * @param linkAddress the value for link.link_address
     *
     * @mbg.generated
     */
    public void setLinkAddress(String linkAddress) {
        this.linkAddress = linkAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_description
     *
     * @return the value of link.link_description
     *
     * @mbg.generated
     */
    public String getLinkDescription() {
        return linkDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_description
     *
     * @param linkDescription the value for link.link_description
     *
     * @mbg.generated
     */
    public void setLinkDescription(String linkDescription) {
        this.linkDescription = linkDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_order
     *
     * @return the value of link.link_order
     *
     * @mbg.generated
     */
    public Integer getLinkOrder() {
        return linkOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_order
     *
     * @param linkOrder the value for link.link_order
     *
     * @mbg.generated
     */
    public void setLinkOrder(Integer linkOrder) {
        this.linkOrder = linkOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link_title
     *
     * @return the value of link.link_title
     *
     * @mbg.generated
     */
    public String getLinkTitle() {
        return linkTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link_title
     *
     * @param linkTitle the value for link.link_title
     *
     * @mbg.generated
     */
    public void setLinkTitle(String linkTitle) {
        this.linkTitle = linkTitle;
    }
}