package com.fdzang.microservice.blog.ucenter.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table options
 */
public class OptionsDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   配置项分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.option_category
     *
     * @mbg.generated
     */
    private String optionCategory;

    /**
     * Database Column Remarks:
     *   配置项值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.option_value
     *
     * @mbg.generated
     */
    private String optionValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.id
     *
     * @return the value of options.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.id
     *
     * @param id the value for options.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.option_category
     *
     * @return the value of options.option_category
     *
     * @mbg.generated
     */
    public String getOptionCategory() {
        return optionCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.option_category
     *
     * @param optionCategory the value for options.option_category
     *
     * @mbg.generated
     */
    public void setOptionCategory(String optionCategory) {
        this.optionCategory = optionCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.option_value
     *
     * @return the value of options.option_value
     *
     * @mbg.generated
     */
    public String getOptionValue() {
        return optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.option_value
     *
     * @param optionValue the value for options.option_value
     *
     * @mbg.generated
     */
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue;
    }
}