package com.fdzang.microservice.blog.ucenter.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
public class UserDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   用户邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_email
     *
     * @mbg.generated
     */
    private String userEmail;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户链接地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_url
     *
     * @mbg.generated
     */
    private String userUrl;

    /**
     * Database Column Remarks:
     *   用户密码，MD5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     * Database Column Remarks:
     *   用户角色，管理员：adminRole，普通用户：defaultRole，访客用户：visitorRole
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_role
     *
     * @mbg.generated
     */
    private String userRole;

    /**
     * Database Column Remarks:
     *   用户文章计数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_article_count
     *
     * @mbg.generated
     */
    private Integer userArticleCount;

    /**
     * Database Column Remarks:
     *   用户已发布文章计数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_published_article_count
     *
     * @mbg.generated
     */
    private Integer userPublishedArticleCount;

    /**
     * Database Column Remarks:
     *   用户头像图片链接地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_avatar
     *
     * @mbg.generated
     */
    private String userAvatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbg.generated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbg.generated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_url
     *
     * @return the value of user.user_url
     *
     * @mbg.generated
     */
    public String getUserUrl() {
        return userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_url
     *
     * @param userUrl the value for user.user_url
     *
     * @mbg.generated
     */
    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_role
     *
     * @return the value of user.user_role
     *
     * @mbg.generated
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_role
     *
     * @param userRole the value for user.user_role
     *
     * @mbg.generated
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_article_count
     *
     * @return the value of user.user_article_count
     *
     * @mbg.generated
     */
    public Integer getUserArticleCount() {
        return userArticleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_article_count
     *
     * @param userArticleCount the value for user.user_article_count
     *
     * @mbg.generated
     */
    public void setUserArticleCount(Integer userArticleCount) {
        this.userArticleCount = userArticleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_published_article_count
     *
     * @return the value of user.user_published_article_count
     *
     * @mbg.generated
     */
    public Integer getUserPublishedArticleCount() {
        return userPublishedArticleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_published_article_count
     *
     * @param userPublishedArticleCount the value for user.user_published_article_count
     *
     * @mbg.generated
     */
    public void setUserPublishedArticleCount(Integer userPublishedArticleCount) {
        this.userPublishedArticleCount = userPublishedArticleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_avatar
     *
     * @return the value of user.user_avatar
     *
     * @mbg.generated
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_avatar
     *
     * @param userAvatar the value for user.user_avatar
     *
     * @mbg.generated
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar;
    }
}