package com.fdzang.microservice.blog.ucenter.dao.mapper;

import com.fdzang.microservice.blog.ucenter.dao.domain.LinkDO;
import com.fdzang.microservice.blog.ucenter.dao.domain.LinkDOExample;
import java.util.List;

public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated
     */
    int insert(LinkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated
     */
    int insertSelective(LinkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated
     */
    List<LinkDO> selectByExample(LinkDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated
     */
    LinkDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LinkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LinkDO record);
}