package com.fdzang.microservice.blog.ucenter.dao.mapper;

import com.fdzang.microservice.blog.ucenter.dao.domain.OptionsDO;
import com.fdzang.microservice.blog.ucenter.dao.domain.OptionsDOExample;
import java.util.List;

public interface OptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated
     */
    int insert(OptionsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated
     */
    int insertSelective(OptionsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated
     */
    List<OptionsDO> selectByExampleWithBLOBs(OptionsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated
     */
    List<OptionsDO> selectByExample(OptionsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated
     */
    OptionsDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OptionsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(OptionsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OptionsDO record);
}