spring:
  datasource:
    username: root
    password: th228614654
    url: jdbc:mysql://118.25.214.237:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://fdzang.top:7001/eureka/,http://fdzang.top:7002/eureka/
  instance:
    prefer-ip-address: true