server:
  port: 7005

spring:
  output:
    ansi:
      enabled: never
  application:
    name: blog-web-ftl
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
    request-context-attribute: request

#global ribbon config
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 15000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

feign:
  hystrix:
    enabled: true

eureka:
  client:
    registry-fetch-interval-seconds: 10 # 每10s获取一次service信息
    service-url:
      defaultZone: http://fdzang.top:7001/eureka/,http://fdzang.top:7002/eureka/
