eureka:
  client:
    registry-fetch-interval-seconds: 10 # 每10s获取一次service信息
    service-url:
      defaultZone: http://thblog.tk:7001/eureka/,http://thblog.tk:7002/eureka/,http://thblog.tk:7003/eureka/
  instance:
    prefer-ip-address: true

